org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17.11

mod_version=1.0.0+mc26.1.2
maven_group=dev.fix85
archives_base_name=soundculling

fabric_version=0.152.1+26.1.2
cloth_config_version=26.1.154
modmenu_version=18.0.0-beta.1
java_version=25
minecraft_dependency=>=26.1
loader_dependency=>=0.19.0
java_dependency=>=25
