org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17.11

mod_version=1.0.0+mc26.2
maven_group=dev.fix85
archives_base_name=soundculling

fabric_version=0.153.0+26.2
cloth_config_version=26.2.155
modmenu_version=20.0.0-beta.4
java_version=25
minecraft_dependency=>=26.2
loader_dependency=>=0.19.0
java_dependency=>=25
